### ISSUE TITLE
As Dev, I want to set an option of whether to show/hide the input diff field to the user

### ISSUE THREAD

**Issue by attilaaf** [MatterPool/boostpow-publish#19]
`showInputDiff: boolean`

If difficulty is set by dev, difficulty displayed is not editable. Otherwise, it is editable. If the slider bar is available, displayed difficulty changes with slider bar.

**Comment by mateuslopes** [comment]
Configuration added as the parameter:
`showInputDiff: false`
Default value is false.
For now it can be showed together with slider bar.
Changes to input reflects to slider, and vice versa.

The editable feature is related to the issue #20 
About the difficulty being set by dev, it can use initialDiff together with lockDiff property to set and lock.
