### ISSUE TITLE
[UI] As a user, when adding boost, difficulty can be entered as a slider bar with information about boost as a percentile.

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-publish#2]
Use boost pow api to get information about percentile. 

Design: https://docs.google.com/document/d/1gQCRIbui8Ah2yH5CB7ya-qncuEFvRaAgrwOCPY_nBA0/edit#heading=h.wi7zlwainm4h
See https://github.com/MatterPool/boostpow-publish/issues/12

Slider bar should use a log scale and display information about pct of boosted content in the last day as user slides across it. 

We also need a label to show 'difficulty' cc @rxxndy  Can you please add 'difficulty' to the mockup ? https://docs.google.com/document/d/1gQCRIbui8Ah2yH5CB7ya-qncuEFvRaAgrwOCPY_nBA0/edit#heading=h.wi7zlwainm4h

**Comment by attilaaf** [comment]
Also allow the developer to turn off the slider and let them control it programmatically from their app (ie: merely passing in to widget)
<img width="1503" alt="hide energy" src="https://user-images.githubusercontent.com/29334536/83441981-a5ff0700-a404-11ea-88bd-849d0a699b60.png">

**Comment by attilaaf** [comment]
Related: https://github.com/MatterPool/boostpow-publish/issues/8

**Comment by DanielKrawisz** [comment]
Slider bar should show both percentile and rank as user moves it.

**Comment by attilaaf** [comment]
3 storypoints

**Comment by attilaaf** [comment]
Omit 'Select Boost Type'; https://docs.google.com/document/d/1gQCRIbui8Ah2yH5CB7ya-qncuEFvRaAgrwOCPY_nBA0/edit#heading=h.wi7zlwainm4h

**Comment by attilaaf** [comment]
https://mm.twetch.com/twetch/pl/r9ooacbp17y7bdqia8a6zcic3r

**Comment by mateuslopes** [comment]
For now, slider component is implemented without fetching API data.
@material-ui/core/Slider component used, dropping the dependency of jquery and of the previous slider library.

Added two new configuration properties:

`sliderDiffStep: 1`
Defines the step value for difficulty slider changes.

`sliderDiffMarkerStep: 10`
Defines the step value to show as a slider marker rule below the slider.

**Comment by mateuslopes** [comment]
I think this is done and can be closed!
The percentile metric changed to a rank metric for now, but percentile is better described on Issue 15, so, we can continue on that issue if needed.
