### ISSUE TITLE
Use logorithmic scale for slider bar. 

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-publish#60]
We expect that boost ranks should be along roughly a logorithmic scale, ie the difficulty differences between earlier ranks is higher than lower ranks. Right now we display the ranks along a linear scale in difficulty. We want to display according to a log scale. 

The details of this scale are described here: https://docs.google.com/document/d/1dewYUTAnJsLeK9nQnbVeoTACnB_i_1foFN1uF0xenmI/edit#heading=h.rmu4pj4u2rj4

We use https://material-ui.com/components/slider/ for our slider. The new slider should be continuous and should internally take on values between 0 and 1 but the displayed value should be the derived difficulty. 

Points: 8

**Comment by pelotom** [comment]
Hey, looks like that document is protected, I requested access.
