### ISSUE TITLE
Display preview of boosted content for users

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-publish#7]
For uploaded files, preview file however we know how.

For hashes, search in database for content related to that hash and preview it if we know how.

**Comment by attilaaf** [comment]
As a developer, I want to have a beautiful and intuitive publisher, so my users can boost arbitrary data in my app.

**Comment by DanielKrawisz** [comment]
Types of content that can be previewed. 
* Unknown
* Content cannot be displayed
* Image 
* Text 
* markdown

**Comment by DanielKrawisz** [comment]
For content provided by app, publish widget must boost hash calculated from provided content (so that the user never boost anything different from what he sees in the preview)

**Comment by attilaaf** [comment]
Extra flags in publisher:

- showContentPreview: boolean (If false, do not show content preview at all)

- if showContentPreview == true, then developer can provide additional setting:

 - contentType
