### ISSUE TITLE
As a Developer, I want to programmatically provide the difficulty, so that I have control over the experience and it is easier for their users.

### ISSUE THREAD

**Issue by attilaaf** [MatterPool/boostpow-publish#8]
Add 2 parameters to publisher:

`difficulty`: number >= 1
`value`: The fee paid for the Boost Output

if `difficulty` is valid, then do not show Energy dropdown and `diffMultiplier` is not used in this case.

Hide the 'Energy' dropdown list because the user in this case cannot change the difficulty.

If the developer wishes to. show the fixed difficulty, then they can use the `displayMessage` property to do so for now.

See: https://publish.boostpow.com/docs.html 

Also update the docs.

<img width="1503" alt="hide energy" src="https://user-images.githubusercontent.com/29334536/83441742-43a60680-a404-11ea-823b-a9c198454ca8.png">

Optionally add a slider they can control

**Comment by attilaaf** [comment]
superseded by https://github.com/MatterPool/boostpow-publish/issues/2

**Comment by attilaaf** [comment]
todo: sketch or mockup

**Comment by mateuslopes** [comment]
Right now this can be accomplished by using the following properties combination:
```
initialDiff: 1,
lockDiff: true,
showInputDiff: false,
showSliderDiff: false,
```
Maybe it could have just one property called: 
`fixedDiff: <number value>`
If fixedDiff > 0 so we apply all the above properties automatically.
